export interface UnderwritingReport {
  property: {
    address: string;
    type: string;
    areaSqm: number;
    rooms: number;
    owner: string;
    titleStatus: string;
  };
  valuationUsd: number;
  valuationRange: [number, number];
  riskScore: number; // 0 (safe) .. 100 (high risk)
  riskFlags: string[];
  summary: string;
  /** true when generated by the local mock (no GEMINI_API_KEY present) */
  mock?: boolean;
}
