"use client";

import { useMemo, useState } from "react";
import { formatUnits, parseUnits } from "viem";
import { useAccount, useChainId, usePublicClient, useReadContract, useWriteContract } from "wagmi";
import { erc20Abi, marketplaceAbi, rwaAbi } from "@/lib/abi";
import { FEE_COLLECTOR, MARKETPLACE_ADDRESS, PLATFORM_FEE_USDC, RWA_ADDRESS, USDC_ADDRESS } from "@/lib/config";
import { xlayerTestnet } from "@/lib/chains";
import { AddNetworkButton } from "@/components/AddNetworkButton";
import { FaucetButton } from "@/components/FaucetButton";
import { friendlyError } from "@/lib/errors";

export default function MarketDetailPage({ params, searchParams }: { params: { tokenId: string }; searchParams?: { intent?: string } }) {
  const tokenId = BigInt(params.tokenId); const { address, isConnected } = useAccount(); const chainId = useChainId(); const client = usePublicClient({ chainId: xlayerTestnet.id }); const { writeContractAsync } = useWriteContract();
  const [buyAmount, setBuyAmount] = useState("10.20"); const [sellAmount, setSellAmount] = useState("1"); const [seedAmount, setSeedAmount] = useState("10"); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(searchParams?.intent === "list" ? "Mint confirmed. Complete the three launch steps below to open this market." : "");
  const empty = "0x0000000000000000000000000000000000000000" as const;
  const { data: asset, refetch: refetchAsset } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "assetInfo", args: [tokenId], chainId: xlayerTestnet.id });
  const { data: pool, refetch: refetchPool } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "pools", args: [tokenId], chainId: xlayerTestnet.id });
  const { data: usdcBalance, refetch: refetchUsdc } = useReadContract({ address: USDC_ADDRESS, abi: erc20Abi, functionName: "balanceOf", args: [address ?? empty], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: shareBalance, refetch: refetchShares } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "balanceOf", args: [address ?? empty, tokenId], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: allowance, refetch: refetchAllowance } = useReadContract({ address: USDC_ADDRESS, abi: erc20Abi, functionName: "allowance", args: [address ?? empty, MARKETPLACE_ADDRESS], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: approved, refetch: refetchApproval } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "isApprovedForAll", args: [address ?? empty, MARKETPLACE_ADDRESS], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const poolTuple = pool as readonly [bigint, bigint, bigint, bigint, boolean] | undefined; const info = asset as { owner?: string; valuationUsd?: bigint; launchValuationUsd?: bigint; riskScore?: number } | undefined; const active = Boolean(poolTuple?.[4]);
  const buyRaw = useMemo(() => safeUnits(buyAmount, 6), [buyAmount]); const sellRaw = useMemo(() => { try { return BigInt(sellAmount || "0"); } catch { return 0n; } }, [sellAmount]); const seedRaw = useMemo(() => safeUnits(seedAmount, 6), [seedAmount]);
  const { data: buyQuote } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "quoteBuy", args: [tokenId, buyRaw], chainId: xlayerTestnet.id, query: { enabled: active && buyRaw > PLATFORM_FEE_USDC } });
  const { data: sellQuote } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "quoteSell", args: [tokenId, sellRaw], chainId: xlayerTestnet.id, query: { enabled: active && sellRaw > 0n } });

  async function transact(label: string, request: Parameters<typeof writeContractAsync>[0]) {
    setBusy(label); setError(""); setNotice("");
    try { const hash = await writeContractAsync({ ...request, chainId: xlayerTestnet.id }); await client?.waitForTransactionReceipt({ hash }); setNotice(`${label} confirmed on X Layer.`); await Promise.all([refetchPool(), refetchUsdc(), refetchShares(), refetchAllowance(), refetchApproval(), refetchAsset()]); }
    catch (caught) { setError(friendlyError(caught, `${label} failed`)); } finally { setBusy(""); }
  }

  const wrongNetwork = chainId !== xlayerTestnet.id; const issuer = Boolean(address && info?.owner?.toLowerCase() === address.toLowerCase()); const seedApprovalRaw = seedRaw + PLATFORM_FEE_USDC; const buyNeedsApproval = (allowance ?? 0n) < buyRaw; const hasSeedFunds = (usdcBalance ?? 0n) >= seedApprovalRaw; const listingStep = !approved ? 1 : (allowance ?? 0n) < seedApprovalRaw ? 2 : 3;
  return <div className="page-frame liquidity-desk">
    <div className="section-heading"><div><p className="kicker">Liquidity desk / asset #{params.tokenId}</p><h1 className="text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Fund the<br />property market.</h1></div><p>USDC_TEST is the settlement asset; OKB is gas only. Fixed protocol fees are visible before every transaction.</p></div>
    <div className="fee-ledger"><span>Listing <strong>$0.20</strong></span><span>Buy <strong>$0.20</strong></span><span>Sell <strong>$0.20</strong></span><span>Collector <strong>{FEE_COLLECTOR.slice(0, 8)}…</strong></span></div>
    {!isConnected && <Panel tone="warning">Connect the wallet that owns or wants to trade this asset.</Panel>}{isConnected && wrongNetwork && <div className="glass-panel mb-4 flex items-center justify-between gap-3 p-4 text-amber-100"><span>Switch to X Layer Testnet to continue.</span><AddNetworkButton /></div>}
    {notice && <Panel tone="success">{notice}</Panel>}{error && <Panel tone="error">{error}</Panel>}
    {info && <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="property-ledger glass-panel"><div className="property-orbit"><span>#{params.tokenId}</span></div><div><p className="kicker">On-chain property record</p><h2>Asset #{params.tokenId}</h2><div className="ledger-stats"><Stat label="AI valuation" value={`$${Number(info.valuationUsd ?? 0n).toLocaleString()}`} /><Stat label="Launch valuation" value={`$${Number(info.launchValuationUsd ?? 0n).toLocaleString()}`} /><Stat label="Risk" value={`${Number(info.riskScore ?? 0)}/100`} /><Stat label="Your shares" value={Number(shareBalance ?? 0n).toLocaleString()} /><Stat label="Your USDC" value={Number(formatUnits(usdcBalance ?? 0n, 6)).toFixed(2)} /></div>{active && poolTuple && <div className="live-pool"><p className="kicker">Live pool</p><div className="ledger-stats"><Stat label="Share reserve" value={Number(poolTuple[0]).toLocaleString()} /><Stat label="USDC reserve" value={`${Number(formatUnits(poolTuple[1], 6)).toFixed(2)} USDC`} /><Stat label="Spot price" value={`$${poolTuple[0] ? (Number(poolTuple[1]) / 1e6 / Number(poolTuple[0])).toFixed(5) : "0"}`} /><Stat label="Locked LP" value={poolTuple[3].toString()} /></div></div>}</div></div>
      <div className="space-y-4">{!active && issuer && <div className="listing-wizard glass-panel"><div><p className="kicker">Launch sequence</p><h2>List this digital property</h2><p>The $10+ seed stays in the pool. The separate $0.20 listing fee funds the protocol.</p></div><div className="wizard-steps">{["Approve shares", "Approve USDC", "Create pool"].map((label, index) => <span className={listingStep > index + 1 ? "done" : listingStep === index + 1 ? "active" : ""} key={label}>{index + 1}<small>{label}</small></span>)}</div>
        <label className="field-label">Liquidity seed<input value={seedAmount} onChange={(event) => setSeedAmount(event.target.value)} inputMode="decimal" /><small>Required from wallet: {Number(formatUnits(seedApprovalRaw, 6)).toFixed(2)} USDC_TEST including listing fee.</small></label>
        {!hasSeedFunds && <div className="faucet-recovery"><p>You need at least {Number(formatUnits(seedApprovalRaw, 6)).toFixed(2)} USDC_TEST.</p><FaucetButton onMinted={() => refetchUsdc()} /></div>}
        {!approved && <button className="button button-primary w-full" disabled={Boolean(busy) || wrongNetwork} onClick={() => transact("Share approval", { address: RWA_ADDRESS, abi: rwaAbi, functionName: "setApprovalForAll", args: [MARKETPLACE_ADDRESS, true] })}>{busy || "Step 1 · Approve asset shares"}</button>}
        {approved && (allowance ?? 0n) < seedApprovalRaw && <button className="button button-primary w-full" disabled={Boolean(busy) || wrongNetwork || !hasSeedFunds} onClick={() => transact("USDC approval", { address: USDC_ADDRESS, abi: erc20Abi, functionName: "approve", args: [MARKETPLACE_ADDRESS, seedApprovalRaw] })}>{busy || `Step 2 · Approve ${Number(formatUnits(seedApprovalRaw, 6)).toFixed(2)} USDC`}</button>}
        {approved && (allowance ?? 0n) >= seedApprovalRaw && <button className="button button-primary w-full" disabled={Boolean(busy) || wrongNetwork || !hasSeedFunds || seedRaw < 10_000_000n} onClick={() => transact("Market creation", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "createPool", args: [tokenId, seedRaw] })}>{busy || "Step 3 · Open market ↗"}</button>}
      </div>}
      {active && <><TradeBox title="Acquire shares" amount={buyAmount} setAmount={setBuyAmount} quote={`${Number(buyQuote ?? 0n).toLocaleString()} shares`} hint="Amount includes the fixed $0.20 buy fee." action={buyNeedsApproval ? () => transact("USDC approval", { address: USDC_ADDRESS, abi: erc20Abi, functionName: "approve", args: [MARKETPLACE_ADDRESS, buyRaw] }) : () => transact("Share purchase", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "buy", args: [tokenId, buyRaw, (buyQuote ?? 0n) * 99n / 100n, BigInt(Math.floor(Date.now() / 1000) + 600)] })} label={buyNeedsApproval ? "Approve USDC" : "Buy shares"} disabled={Boolean(busy) || wrongNetwork || buyRaw <= PLATFORM_FEE_USDC} /><TradeBox title="Release shares" amount={sellAmount} setAmount={setSellAmount} quote={`${Number(formatUnits(sellQuote ?? 0n, 6)).toFixed(4)} USDC net`} hint="The fixed $0.20 sell fee is deducted from proceeds." action={!approved ? () => transact("Share approval", { address: RWA_ADDRESS, abi: rwaAbi, functionName: "setApprovalForAll", args: [MARKETPLACE_ADDRESS, true] }) : () => transact("Share sale", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "sell", args: [tokenId, sellRaw, (sellQuote ?? 0n) * 99n / 100n, BigInt(Math.floor(Date.now() / 1000) + 600)] })} label={!approved ? "Approve shares" : "Sell shares"} disabled={Boolean(busy) || wrongNetwork || sellRaw <= 0n} /></>}
      {!active && !issuer && <Panel tone="warning">Only the original issuer can seed and open this market.</Panel>}</div></div>}
  </div>;
}
function safeUnits(value: string, decimals: number) { try { return parseUnits(value || "0", decimals); } catch { return 0n; } }
function Stat({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ children, tone }: { children: React.ReactNode; tone: "warning" | "success" | "error" }) { const color = tone === "success" ? "text-emerald-200" : tone === "error" ? "text-red-200" : "text-amber-100"; return <div className={`glass-panel mb-4 p-4 text-sm ${color}`}>{children}</div>; }
function TradeBox({ title, amount, setAmount, quote, hint, action, label, disabled }: { title: string; amount: string; setAmount: (value: string) => void; quote: string; hint: string; action: () => void; label: string; disabled: boolean }) { return <div className="trade-box glass-panel"><p className="kicker">{title}</p><input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal"/><p>Estimated output: <strong>{quote}</strong> · 1% slippage protection</p><small>{hint}</small><button className="button button-primary w-full" onClick={action} disabled={disabled}>{label}</button></div>; }
