"use client";

import { useMemo, useState } from "react";
import { formatUnits, parseUnits } from "viem";
import { useAccount, useChainId, usePublicClient, useReadContract, useWriteContract } from "wagmi";
import { erc20Abi, marketplaceAbi, rwaAbi } from "@/lib/abi";
import { MARKETPLACE_ADDRESS, RWA_ADDRESS, USDC_ADDRESS } from "@/lib/config";
import { xlayerTestnet } from "@/lib/chains";
import { AddNetworkButton } from "@/components/AddNetworkButton";

export default function MarketDetailPage({ params }: { params: { tokenId: string } }) {
  const tokenId = BigInt(params.tokenId);
  const { address, isConnected } = useAccount(); const chainId = useChainId(); const client = usePublicClient({ chainId: xlayerTestnet.id }); const { writeContractAsync } = useWriteContract();
  const [buyAmount, setBuyAmount] = useState("1"); const [sellAmount, setSellAmount] = useState("1"); const [seedAmount, setSeedAmount] = useState("10"); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const { data: asset, refetch: refetchAsset } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "assetInfo", args: [tokenId], chainId: xlayerTestnet.id });
  const { data: pool, refetch: refetchPool } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "pools", args: [tokenId], chainId: xlayerTestnet.id });
  const { data: usdcBalance, refetch: refetchUsdc } = useReadContract({ address: USDC_ADDRESS, abi: erc20Abi, functionName: "balanceOf", args: [address ?? "0x0000000000000000000000000000000000000000"], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: shareBalance, refetch: refetchShares } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "balanceOf", args: [address ?? "0x0000000000000000000000000000000000000000", tokenId], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: allowance, refetch: refetchAllowance } = useReadContract({ address: USDC_ADDRESS, abi: erc20Abi, functionName: "allowance", args: [address ?? "0x0000000000000000000000000000000000000000", MARKETPLACE_ADDRESS], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const { data: approved, refetch: refetchApproval } = useReadContract({ address: RWA_ADDRESS, abi: rwaAbi, functionName: "isApprovedForAll", args: [address ?? "0x0000000000000000000000000000000000000000", MARKETPLACE_ADDRESS], chainId: xlayerTestnet.id, query: { enabled: Boolean(address) } });
  const poolTuple = pool as readonly [bigint, bigint, bigint, bigint, boolean] | undefined; const info = asset as any; const active = Boolean(poolTuple?.[4]);
  const buyRaw = useMemo(() => { try { return parseUnits(buyAmount || "0", 6); } catch { return 0n; } }, [buyAmount]); const sellRaw = useMemo(() => { try { return BigInt(sellAmount || "0"); } catch { return 0n; } }, [sellAmount]);
  const { data: buyQuote } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "quoteBuy", args: [tokenId, buyRaw], chainId: xlayerTestnet.id, query: { enabled: active && buyRaw > 0n } });
  const { data: sellQuote } = useReadContract({ address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "quoteSell", args: [tokenId, sellRaw], chainId: xlayerTestnet.id, query: { enabled: active && sellRaw > 0n } });

  async function transact(label: string, request: any) { setBusy(label); setError(""); setNotice(""); try { const hash = await writeContractAsync({ ...request, chainId: xlayerTestnet.id }); await client?.waitForTransactionReceipt({ hash }); setNotice(`${label} confirmed on X Layer.`); await Promise.all([refetchPool(), refetchUsdc(), refetchShares(), refetchAllowance(), refetchApproval(), refetchAsset()]); } catch (caught) { setError(caught instanceof Error ? caught.message : `${label} failed`); } finally { setBusy(""); } }
  const wrongNetwork = chainId !== xlayerTestnet.id; const issuer = address && info?.owner?.toLowerCase() === address.toLowerCase(); const seedRaw = (() => { try { return parseUnits(seedAmount || "0", 6); } catch { return 0n; } })();

  return <div className="page-frame"><div className="section-heading"><div><p className="kicker">Marketplace / asset #{params.tokenId}</p><h1 className="text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Trade the<br />property.</h1></div><p>Initial price is anchored to the conservative AI launch valuation. Every swap has a 0.30% LP fee.</p></div>
    {!isConnected && <div className="glass-panel mb-4 p-4 text-amber-200">Connect a wallet to trade or seed liquidity.</div>}{wrongNetwork && isConnected && <div className="glass-panel mb-4 flex items-center justify-between p-4 text-amber-200"><span>Switch to X Layer Testnet.</span><AddNetworkButton /></div>}
    {info && <div className="grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><div className="glass-panel p-6"><p className="kicker">Verified on-chain asset</p><h2 className="mt-3 text-3xl font-semibold">Asset #{params.tokenId}</h2><div className="mt-8 grid grid-cols-2 gap-4 text-sm"><Stat label="AI valuation" value={`$${Number(info.valuationUsd).toLocaleString()}`} /><Stat label="Launch valuation" value={`$${Number(info.launchValuationUsd).toLocaleString()}`} /><Stat label="Total shares" value={Number(info.totalShares).toLocaleString()} /><Stat label="Risk" value={`${Number(info.riskScore)}/100`} /><Stat label="Your shares" value={Number(shareBalance ?? 0n).toLocaleString()} /><Stat label="Your USDC" value={Number(formatUnits(usdcBalance ?? 0n, 6)).toFixed(2)} /></div>{active && poolTuple && <div className="mt-6 rounded-xl border border-cyan-200/10 bg-cyan-200/[.03] p-4"><p className="kicker">Live pool</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><Stat label="Share reserve" value={Number(poolTuple[0]).toLocaleString()} /><Stat label="USDC reserve" value={`${Number(formatUnits(poolTuple[1], 6)).toFixed(2)} USDC`} /><Stat label="Spot price" value={`$${(Number(poolTuple[1]) / 1e6 / Number(poolTuple[0])).toFixed(4)}`} /><Stat label="Locked LP" value={poolTuple[3].toString()} /></div></div>}</div>
    <div className="space-y-4">{!active && issuer && <div className="glass-panel p-5"><p className="kicker">Launch liquidity</p><h2 className="mt-2 text-xl font-semibold">Seed the market</h2><p className="mt-2 text-sm text-white/50">Deposit at least 10 USDC_TEST plus valuation-matched shares. The minimum LP remains permanently locked.</p><input className="mt-5 w-full rounded-xl border border-white/10 bg-black/20 p-3" value={seedAmount} onChange={(e) => setSeedAmount(e.target.value)} inputMode="decimal" />{!approved && <button className="button button-ghost mt-3 w-full" disabled={Boolean(busy) || wrongNetwork} onClick={() => transact("Share approval", { address: RWA_ADDRESS, abi: rwaAbi, functionName: "setApprovalForAll", args: [MARKETPLACE_ADDRESS, true] })}>Approve asset shares</button>}{(allowance ?? 0n) < seedRaw && <button className="button button-ghost mt-3 w-full" disabled={Boolean(busy) || wrongNetwork} onClick={() => transact("USDC approval", { address: USDC_ADDRESS, abi: erc20Abi, functionName: "approve", args: [MARKETPLACE_ADDRESS, seedRaw] })}>Approve {seedAmount || "0"} USDC</button>}<button className="button button-primary mt-3 w-full" disabled={Boolean(busy) || wrongNetwork || !approved || (allowance ?? 0n) < seedRaw || seedRaw < 10_000_000n} onClick={() => transact("Market creation", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "createPool", args: [tokenId, seedRaw] })}>{busy || "Create liquid market ↗"}</button></div>}
    {active && <><TradeBox title="Buy shares" amount={buyAmount} setAmount={setBuyAmount} quote={`${Number(buyQuote ?? 0n).toLocaleString()} shares`} action={(allowance ?? 0n) < buyRaw ? () => transact("USDC approval", { address: USDC_ADDRESS, abi: erc20Abi, functionName: "approve", args: [MARKETPLACE_ADDRESS, buyRaw] }) : () => transact("Share purchase", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "buy", args: [tokenId, buyRaw, (buyQuote ?? 0n) * 99n / 100n, BigInt(Math.floor(Date.now()/1000)+600)] })} label={(allowance ?? 0n) < buyRaw ? "Approve USDC" : "Buy shares"} disabled={Boolean(busy) || wrongNetwork || buyRaw <= 0n} /><TradeBox title="Sell shares" amount={sellAmount} setAmount={setSellAmount} quote={`${Number(formatUnits(sellQuote ?? 0n, 6)).toFixed(4)} USDC`} action={!approved ? () => transact("Share approval", { address: RWA_ADDRESS, abi: rwaAbi, functionName: "setApprovalForAll", args: [MARKETPLACE_ADDRESS, true] }) : () => transact("Share sale", { address: MARKETPLACE_ADDRESS, abi: marketplaceAbi, functionName: "sell", args: [tokenId, sellRaw, (sellQuote ?? 0n) * 99n / 100n, BigInt(Math.floor(Date.now()/1000)+600)] })} label={!approved ? "Approve shares" : "Sell shares"} disabled={Boolean(busy) || wrongNetwork || sellRaw <= 0n} /></>}
    {!active && !issuer && <div className="glass-panel p-5 text-amber-100">This asset has not been listed by its issuer yet.</div>}{error && <div className="glass-panel p-4 text-sm text-red-200">{error}</div>}{notice && <div className="glass-panel p-4 text-sm text-emerald-200">{notice}</div>}</div></div>}</div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-white/40">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function TradeBox({ title, amount, setAmount, quote, action, label, disabled }: { title: string; amount: string; setAmount: (value: string) => void; quote: string; action: () => void; label: string; disabled: boolean }) { return <div className="glass-panel p-5"><p className="kicker">{title}</p><input className="mt-4 w-full rounded-xl border border-white/10 bg-black/20 p-3" value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal"/><p className="mt-2 text-xs text-white/45">Estimated output: {quote} · 1% slippage protection</p><button className="button button-primary mt-4 w-full" onClick={action} disabled={disabled}>{label}</button></div>; }
