"use client";

import Link from "next/link";
import { motion, useMotionTemplate, useScroll, useSpring, useTransform } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { ScrambleIn } from "./ScrambleText";
import { BuildSequence } from "./BuildSequence";

const VIDEOS = {
  hero: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_083515_290e5a10-0b95-41af-a5e2-32b6389baa4d.mp4",
  evidence: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_092455_089c54f8-3b03-4966-9df1-e9746063d0ef.mp4",
  metrics: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_095810_ecea3dd2-fc5e-4e41-8696-4219290b6589.mp4",
  market: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_095750_32a52ce0-2005-45c9-9093-41f03fde9530.mp4",
  footer: "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_080203_fd7f4f85-3a86-4837-8192-85e7bfe68e75.mp4",
};

export function CinematicHome() {
  const videoRef = useRef<HTMLVideoElement>(null); const sectionRef = useRef<HTMLElement>(null); const [entered, setEntered] = useState(false); const seeking = useRef(false); const target = useRef(0);
  const { scrollYProgress } = useScroll({ target: sectionRef, offset: ["start end", "end start"] }); const smooth = useSpring(scrollYProgress, { stiffness: 15, damping: 32, mass: 1.8 }); const y = useTransform(smooth, [0.3, 0.8], [60, -120]); const rotate = useTransform(smooth, [0.2, 0.8], [24, 4]); const opacity = useTransform(smooth, [0.3, 0.5], [0, 1]); const transform = useMotionTemplate`perspective(400px) rotateX(${rotate}deg) translateY(${y}px) translateZ(15px)`;
  useEffect(() => { const timer = setTimeout(() => setEntered(true), 800); return () => clearTimeout(timer); }, []);
  useEffect(() => { const video = videoRef.current; if (!video) return; const seek = () => { if (seeking.current || !Number.isFinite(video.duration)) return; seeking.current = true; video.currentTime = Math.max(0, Math.min(video.duration - 0.05, target.current)); }; const move = (event: MouseEvent) => { target.current = Math.max(0, Math.min(video.duration || 0, target.current + event.movementX / window.innerWidth * (video.duration || 1) * 0.8)); seek(); }; const done = () => { seeking.current = false; if (Math.abs(video.currentTime - target.current) > 0.04) seek(); }; window.addEventListener("mousemove", move); video.addEventListener("seeked", done); return () => { window.removeEventListener("mousemove", move); video.removeEventListener("seeked", done); }; }, []);
  return <div className="cinematic-home">
    <section className="cinematic-screen"><video ref={videoRef} className="cinematic-video" src={VIDEOS.hero} muted playsInline preload="metadata"/><div className="cinematic-shade"/><div className="cinematic-dots"/><div className="cinematic-watermark">TOKENIZED</div><motion.div className="cinematic-hero-content" animate={{ opacity: entered ? 1 : 0 }} transition={{ duration: 1 }}><div className="cinematic-spacer"/><div className="cinematic-bottom"><div><h1><ScrambleIn text="Anything Real" delay={200} triggered={entered}/><br/><ScrambleIn text="Into Equity" delay={500} triggered={entered}/></h1><motion.p initial={{ opacity: 0, y: 25 }} animate={entered ? { opacity: 1, y: 0 } : {}} transition={{ duration: .9, delay: .2 }}>A laptop, camera, watch, cup, vehicle, collectible, or other physical asset becomes an AI-valued NFT with liquid fractional shares on X Layer.</motion.p></div><div className="cinematic-right"><h1><ScrambleIn text="One Photo" delay={700} triggered={entered}/><br/><ScrambleIn text="Open Market" delay={1000} triggered={entered}/></h1><div className="hero-actions"><Link className="button button-primary" href="/tokenize">Tokenize an asset ↗</Link><Link className="button button-ghost" href="/marketplace">Open marketplace</Link></div></div></div></motion.div></section>
    <section ref={sectionRef} className="cinematic-screen"><VideoBackground src={VIDEOS.evidence}/><motion.p style={{ transform, opacity }} className="cinematic-statement">Upload a clear asset photo instead of confidential ownership paperwork. AI identifies the item, estimates conservative resale value, flags manipulation or prohibited goods, and signs a mint authorization the browser cannot forge.</motion.p></section>
    <BuildSequence />
    <section className="cinematic-screen cinematic-metrics"><VideoBackground src={VIDEOS.metrics}/><p className="cinematic-kicker">Asset protocol metrics</p><div className="cinematic-metric-grid">{[["1M", "Shares per asset"], ["$10", "Minimum USDC liquidity"], ["$0.20", "Platform fee per action"]].map(([value,label], index) => <motion.div key={label} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .3 }} transition={{ delay: index*.15 }}><strong>{value}</strong><span>{label}</span></motion.div>)}</div></section>
    <section className="cinematic-screen cinematic-tech"><VideoBackground src={VIDEOS.market}/><div className="cinematic-tech-top"><motion.h2 initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>Valuation<br/>Into Liquidity</motion.h2><motion.p initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>Every market launches from Gemini’s conservative lower-bound resale valuation. The issuer seeds USDC and matching shares; traders buy or sell through a permanent-liquidity AMM.</motion.p></div><div className="cinematic-feature-grid">{[["Photo-First Gate","Recognizes physical goods without demanding private documents."],["Signed Mint","EIP-712 authorization binds report, image, wallet, and valuation."],["USDC Pool","The first $10 of liquidity remains permanently locked."],["Transparent Fees","Listing, buying, and selling each cost a fixed $0.20 USDC."]].map(([title,body], index)=><motion.div key={title} initial={{ opacity:0,y:20 }} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.1}}><h3>{title}</h3><p>{body}</p></motion.div>)}</div></section>
    <footer className="cinematic-footer"><video src={VIDEOS.footer} autoPlay muted loop playsInline/><div><p className="kicker">XLAYER ESTATE PROTOCOL</p><h2>Physical assets.<br/>Programmable markets.</h2><p>AI-assisted asset records and USDC liquidity infrastructure on X Layer testnet.</p></div></footer>
  </div>;
}

function VideoBackground({ src }: { src: string }) { return <><video className="cinematic-video" src={src} autoPlay muted loop playsInline preload="none"/><div className="cinematic-shade"/></>; }
